version: "3.8"

services:
  disbursement:
    platform: linux/amd64
    ports:
        - 3000:3000
    build:
        context: .
        dockerfile: Dockerfile
    container_name: disbursement
    env_file:
        - docker.env
    volumes:
        - ./:/go/src/disbursement
    networks:
      - local
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: postgres
    image: postgres:12.0-alpine
    environment:
      POSTGRES_DB: disbursement
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/disbursement
    volumes:
      - .docker/postgres-data:/var/lib/postgresql/data/disbursement
    ports:
      - "5432:5432"
    networks:
      - local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  uploads:
networks:
  local:
    driver: bridge